services:
  # Sonarr
  sonarr:
    labels:
      - traefik.backend=sonarr
      - traefik.frontend.rule=Host:${DOMAIN}; PathPrefixStrip: /sonarr
      - traefik.docker.network=proxied
      - traefik.port=8989
    expose:
      - 8989
