services:
  # Ombi
  ombi:
    labels:
      - traefik.backend=ombi
      - traefik.frontend.rule=Host:${DOMAIN}; PathPrefixStrip: /ombi
      - traefik.docker.network=proxied
      - traefik.port=3579
    expose:
      - 3579
