services:
  # Lidarr
  lidarr:
    labels:
      - traefik.backend=lidarr
      - traefik.frontend.rule=Host:${DOMAIN}; PathPrefixStrip: /lidarr
      - traefik.docker.network=proxied
      - traefik.port=8686
    expose:
      - 8686
