services:
  # Organizr
  organizr:
    labels:
      - traefik.backend=organizr
      - traefik.frontend.rule=Host:${DOMAIN}; PathPrefixStrip: /organizr
      - traefik.docker.network=proxied
      - traefik.port=80
    expose:
      - 80
