services:
  # Jackett
  jackett:
    labels:
      - traefik.backend=jackett
      - "traefik.frontend.rule=Host:${DOMAIN}; PathPrefixStrip: /jackett"
      - traefik.docker.network=proxied
      - traefik.port=9117
    expose:
      - 9117
